<!DOCTYPE html>
<html>
<head>

<meta charset='utf-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'>
<meta name='apple-touch-fullscreen'       content='yes'>
<meta name='apple-mobile-web-app-capable' content='yes'>
<meta name='apple-mobile-web-app-status-bar-style' content='rgba(228,228,228,1.0)'>

<title>Class: Sketchup::Edge &mdash; SketchUp Ruby APIÂ main</title>

<link rel='stylesheet'  type='text/css' href='../../css/y_fonts.css' />
<link rel='stylesheet'  type='text/css' href='../../css/highlight.github.css' />
<link rel='stylesheet'  type='text/css' href='../../css/y_style.css' />
<link rel='stylesheet'  type='text/css' href='../../css/y_list.css' />
<link rel='stylesheet'  type='text/css' href='../../css/y_color.css' />

<script type='text/javascript'>
  var pathId = "Sketchup::Edge",
    relpath = '../';

  var t2Info = {
    CSEP: '.',
    ISEP: '#',
    NSEP: '::'
  };
</script>

<script type='text/javascript' charset='utf-8' src='../../js/highlight.pack.js'></script>
<script type='text/javascript' charset='utf-8' src='../../js/y_app.js'></script>

</head>
<body>
<svg id='y_wait' class viewBox='0 0 90 90'></svg>
<div id='settings' class='hidden'></div>
<div id='y_list' class='d h'>
  <header id='list_header'></header>
  <nav id= 'list_nav' class='y_nav l_nav'>
    <ul id='list_items'></ul>
  </nav>
</div>
<div id='y_toc' class='f h'>
  <header id='toc_header'></header>
  <nav id= 'toc_nav' class='y_nav t_nav'>
  <ol id='toc_items'></ol>
  </nav>
</div>
<div id='y_main' tabindex='-1'>
  <header id='y_header'>
    <div id='y_menu'>
      <a id='home_no_xhr' href='/'>Home</a> &raquo; 
      <a href='../'>SketchUp</a> &raquo; 
      <a href='../_index.html#alpha_E'>Index (E)</a> &raquo; 
        <a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a> &raquo; 
      <span class='title'><a id='t2_doc_top' href='#'>Edge&nbsp;&#x25B2;</a></span>
    </div>

    <a id='list_href' href="../class_list.html"></a>
    <div id='y_measure_em' class='y_measure'></div>
    <div id='y_measure_vh' class='y_measure'></div>
    <span id='y_measure_50pre' class='y_measure'><code>123456789_123456789_123456789_123456789_123456789_</code></span>
  </header>
<div id='content' class='class'>
<h1>Class: Sketchup::Edge</h1>
<div id='t2_rel_sf_div'>
<table id='t2_rel_sf' class='y_box'>
  <thead>
    <tr><td id='t2_relations' colspan='2'>Relationships</td></tr>
  </thead>
  <tbody>
    <tr><td class='box_h' colspan='2'>Super Chains via Extension / Inclusion / Inheritance</td></tr>
    <tr>
      <td colspan='2'>
        <div class='box_2'>Class Chain:</div>
        <div class='box_22'>
          self,
          <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a>,
          <a href="Entity.html" title="Sketchup::Entity (class)"><code>Entity</code></a>
        </div>
      </td>
    </tr>
    <tr>
      <td colspan='2'>
        <div class='box_2'>Instance Chain:</div>
        <div class='box_22'>
          self,
          <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a>,
          <a href="Entity.html" title="Sketchup::Entity (class)"><code>Entity</code></a>
        </div>
      </td>
    </tr>
    <tr>
      <td id='t2_inherits' class='box_2 o'>Inherits:</td>
      <td class='box_rel'>
        <span class='inheritName'><a href="Drawingelement.html" title="Sketchup::Drawingelement (class)">Sketchup::Drawingelement</a></span>
        <ul class='fullTree'>
          <li>Object</li>
          <li class='next'><a href="Entity.html" title="Sketchup::Entity (class)">Sketchup::Entity</a></li>
          <li class='next'><a href="Drawingelement.html" title="Sketchup::Drawingelement (class)">Sketchup::Drawingelement</a></li>
          <li class='next'>Sketchup::Edge</li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>
</div>
<h2 id='h2_overview'>Overview</h2>
<div id='overview_ds'>
<div class='docstring'>
  <div class='discussion'>
    
<p>The Edge class contains methods modifying and extracting information for edges.</p>

  </div>
</div>
<div class='tags'>
  <p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>
</div>
<h2 class='h2_sum' id='instance_attribute_summary'>Instance Attribute Summary</h2>
<div class='div_sum'>
<ul class='summary full'>
  <li>
    <span class='summary_signature rw'>
      <a href="#smooth=-instance_method" title="#smooth= (instance method)">#<strong>smooth=</strong>(value)  &#x21d2; Boolean </a>
    </span>
    <span class='note title rw'>rw</span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#smooth=-instance_method" title="Sketchup::Edge#smooth= (method)">#smooth=</a> method is used to set the edge to be smooth.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature rw'>
      <a href="#smooth%3F-instance_method" title="#smooth? (instance method)">#<strong>smooth?</strong>  &#x21d2; Boolean </a>
    </span>
    <span class='note title rw'>rw</span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#smooth%3F-instance_method" title="Sketchup::Edge#smooth? (method)">#smooth?</a> method is used to retrieve the current smooth setting for an edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature rw'>
      <a href="#soft=-instance_method" title="#soft= (instance method)">#<strong>soft=</strong>(value)  &#x21d2; Boolean </a>
    </span>
    <span class='note title rw'>rw</span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#soft=-instance_method" title="Sketchup::Edge#soft= (method)">#soft=</a> method is used to set the edge to be soft.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature rw'>
      <a href="#soft%3F-instance_method" title="#soft? (instance method)">#<strong>soft?</strong>  &#x21d2; Boolean </a>
    </span>
    <span class='note title rw'>rw</span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#soft%3F-instance_method" title="Sketchup::Edge#soft? (method)">#soft?</a> method is used to retrieve the current soft setting for an edge.</p></div>
    </div>
  </li>
</ul>

<h3 class='inherited'><a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> - Inherited</h3>
<div class='inherited'><table class='inherited'>
  <tbody>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#casts_shadows=-instance_method" title="Sketchup::Drawingelement#casts_shadows= (method)">#casts_shadows=</a></td>
      <td><div class='inline'><p>The casts_shadows= method is used to set the <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> to cast shadows.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#casts_shadows%3F-instance_method" title="Sketchup::Drawingelement#casts_shadows? (method)">#casts_shadows?</a></td>
      <td><div class='inline'><p>The casts_shadows? method is used to determine if the <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> is casting shadows.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#hidden=-instance_method" title="Sketchup::Drawingelement#hidden= (method)">#hidden=</a></td>
      <td><div class='inline'><p>The hidden= method is used to set the hidden status for an element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#hidden%3F-instance_method" title="Sketchup::Drawingelement#hidden? (method)">#hidden?</a></td>
      <td><div class='inline'><p>The hidden? method is used to determine if the element is hidden.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#layer-instance_method" title="Sketchup::Drawingelement#layer (method)">#layer</a></td>
      <td><div class='inline'><p>The layer method is used to retrieve the <a href="Layer.html" title="Sketchup::Layer (class)"><code>Layer</code></a> object of the drawing element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#layer=-instance_method" title="Sketchup::Drawingelement#layer= (method)">#layer=</a></td>
      <td><div class='inline'><p>The layer= method is used to set the layer for the drawing element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#material-instance_method" title="Sketchup::Drawingelement#material (method)">#material</a></td>
      <td><div class='inline'><p>The material method is used to retrieve the material for the drawing element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#material=-instance_method" title="Sketchup::Drawingelement#material= (method)">#material=</a></td>
      <td><div class='inline'><p>The material= method is used to set the material for the drawing element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#receives_shadows=-instance_method" title="Sketchup::Drawingelement#receives_shadows= (method)">#receives_shadows=</a></td>
      <td><div class='inline'><p>The receive_shadows= method is used to set the <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> to receive shadows.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#receives_shadows%3F-instance_method" title="Sketchup::Drawingelement#receives_shadows? (method)">#receives_shadows?</a></td>
      <td><div class='inline'><p>The receive_shadows? method is used to determine if the <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> is receiving shadows.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#visible=-instance_method" title="Sketchup::Drawingelement#visible= (method)">#visible=</a></td>
      <td><div class='inline'><p>The visible= method is used to set the visible status for an element.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m rw' href="Drawingelement.html#visible%3F-instance_method" title="Sketchup::Drawingelement#visible? (method)">#visible?</a></td>
      <td><div class='inline'><p>The visible? method is used to get the visible status for an element.</p></div></td>
    </tr>
  </tbody>
</table></div>

<h3 class='inherited'><a href="Entity.html" title="Sketchup::Entity (class)"><code>Entity</code></a> - Inherited</h3>
<div class='inherited'><table class='inherited'>
  <tbody>
    <tr class='i_ds'>
      <td><a class='i_m ro' href="Entity.html#deleted%3F-instance_method" title="Sketchup::Entity#deleted? (method)">#deleted?</a></td>
      <td><div class='inline'><p>The deleted? method is used to determine if your entity is still valid (not deleted by another script, for example.).</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ro' href="Entity.html#valid%3F-instance_method" title="Sketchup::Entity#valid? (method)">#valid?</a></td>
      <td><div class='inline'><p>The <code>#valid?</code> method is used to determine if your entity is still valid (not deleted by another script, for example).</p></div></td>
    </tr>
  </tbody>
</table></div>
</div>  <!-- instance_attribute_summary -->

<h2 class='h2_sum' id='instance_method_summary'>Instance Method Summary</h2>
<div class='div_sum'>
<ul class='summary full'>
  <li>
    <span class='summary_signature '>
      <a href="#all_connected-instance_method" title="#all_connected (instance method)">#<strong>all_connected</strong>  &#x21d2; Array&lt;Sketchup::Entity&gt; </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The all_connected method retrieves all of the entities connected to an edge, including the edge itself.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#common_face-instance_method" title="#common_face (instance method)">#<strong>common_face</strong>(edge2)  &#x21d2; Sketchup::Face<sup>?</sup> </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The common_face method is used to identify a face that is common to two edges.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#curve-instance_method" title="#curve (instance method)">#<strong>curve</strong>  &#x21d2; Sketchup::Curve<sup>?</sup> </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The curve method is used to get the <a href="Curve.html" title="Sketchup::Curve (class)"><code>Curve</code></a> object that this edge belongs to, if any.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#end-instance_method" title="#end (instance method)">#<strong>end</strong>  &#x21d2; Sketchup::Vertex </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The end method is used to retrieve the <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object at the end of the edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#explode_curve-instance_method" title="#explode_curve (instance method)">#<strong>explode_curve</strong>  &#x21d2; Sketchup::Edge </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The explode_curve method is used to explode the curve that the given edge is a part of.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#faces-instance_method" title="#faces (instance method)">#<strong>faces</strong>  &#x21d2; Array&lt;Sketchup::Face&gt; </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#faces-instance_method" title="Sketchup::Edge#faces (method)">#faces</a> method is used to retrieve all of the faces common to the edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#find_faces-instance_method" title="#find_faces (instance method)">#<strong>find_faces</strong>  &#x21d2; Integer </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The find_faces method is used to create all of the Faces that can be created with this edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#length-instance_method" title="#length (instance method)">#<strong>length</strong>  &#x21d2; Length </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#length-instance_method" title="Sketchup::Edge#length (method)">#length</a> method is used to retrieve the length of an edge in current units.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#line-instance_method" title="#line (instance method)">#<strong>line</strong>  &#x21d2; Array(Geom::Point3d, Geom::Vector3d) </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The line method is used to retrieve the line defined by the edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#other_vertex-instance_method" title="#other_vertex (instance method)">#<strong>other_vertex</strong>(vertex1)  &#x21d2; Sketchup::Vertex </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The other_vertex method is used to find the opposite vertex given one vertex of the edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#reversed_in%3F-instance_method" title="#reversed_in? (instance method)">#<strong>reversed_in?</strong>(face)  &#x21d2; Boolean </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The <a href="#reversed_in%3F-instance_method" title="Sketchup::Edge#reversed_in? (method)">#reversed_in?</a> method is used to determine if the edge is reversed in a faceâs bounding loop.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#split-instance_method" title="#split (instance method)">#<strong>split</strong>(position)  &#x21d2; Sketchup::Edge </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The split method is used to  to split an edge into two or more distinct edges.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#start-instance_method" title="#start (instance method)">#<strong>start</strong>  &#x21d2; Sketchup::Vertex </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The start method is used to retrieve the <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object at the start of the edge.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#used_by%3F-instance_method" title="#used_by? (instance method)">#<strong>used_by?</strong>(element)  &#x21d2; Boolean </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The used_by? method is used to see if an edge is used by a given <a href="Face.html" title="Sketchup::Face (class)"><code>Face</code></a> or <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a>.</p></div>
    </div>
  </li>
  <li>
    <span class='summary_signature '>
      <a href="#vertices-instance_method" title="#vertices (instance method)">#<strong>vertices</strong>  &#x21d2; Array&lt;Sketchup::Vertex&gt; </a>
    </span>
    <div class='summary_desc'>
      <div class='inline'><p>The vertices method is used to retrieve the vertices on the edge.</p></div>
    </div>
  </li>
</ul>

<h3 class='inherited'><a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a> - Inherited</h3>
<div class='inherited'><table class='inherited'>
  <tbody>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Drawingelement.html#bounds-instance_method" title="Sketchup::Drawingelement#bounds (method)">#bounds</a></td>
      <td><div class='inline'><p>The <code>#bounds</code> method is used to retrieve the <a href="../Geom/BoundingBox.html" title="Geom::BoundingBox (class)"><code>::Geom::BoundingBox</code></a> bounding a <a href="Drawingelement.html" title="Sketchup::Drawingelement (class)"><code>Drawingelement</code></a>.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Drawingelement.html#erase!-instance_method" title="Sketchup::Drawingelement#erase! (method)">#erase!</a></td>
      <td><div class='inline'><p>The <code>#erase!</code> method is used to erase an element from the model.</p></div></td>
    </tr>
  </tbody>
</table></div>

<h3 class='inherited'><a href="Entity.html" title="Sketchup::Entity (class)"><code>Entity</code></a> - Inherited</h3>
<div class='inherited'><table class='inherited'>
  <tbody>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#add_observer-instance_method" title="Sketchup::Entity#add_observer (method)">#add_observer</a></td>
      <td><div class='inline'><p>The add_observer method is used to add an observer to the current object.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#attribute_dictionaries-instance_method" title="Sketchup::Entity#attribute_dictionaries (method)">#attribute_dictionaries</a></td>
      <td><div class='inline'><p>The attribute_dictionaries method is used to retrieve the <a href="AttributeDictionaries.html" title="Sketchup::AttributeDictionaries (class)"><code>AttributeDictionaries</code></a> collection attached to the entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#attribute_dictionary-instance_method" title="Sketchup::Entity#attribute_dictionary (method)">#attribute_dictionary</a></td>
      <td><div class='inline'><p>The attribute_dictionary method is used to retrieve an attribute dictionary with a given name that is attached to an <a href="Entity.html" title="Sketchup::Entity (class)"><code>Entity</code></a>.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#delete_attribute-instance_method" title="Sketchup::Entity#delete_attribute (method)">#delete_attribute</a></td>
      <td><div class='inline'><p>The <code>#delete_attribute</code> method is used to delete an attribute from an entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#entityID-instance_method" title="Sketchup::Entity#entityID (method)">#entityID</a></td>
      <td><div class='inline'><p>The entityID method is used to retrieve a unique ID assigned to an entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#get_attribute-instance_method" title="Sketchup::Entity#get_attribute (method)">#get_attribute</a></td>
      <td><div class='inline'><p>The <code>#get_attribute</code> method is used to retrieve the value of an attribute in the entityâs attribute dictionary.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#inspect-instance_method" title="Sketchup::Entity#inspect (method)">#inspect</a></td>
      <td><div class='inline'><p>The <code>#inspect</code> method is used to retrieve the string representation of the entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#model-instance_method" title="Sketchup::Entity#model (method)">#model</a></td>
      <td><div class='inline'><p>The model method is used to retrieve the model for the entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#parent-instance_method" title="Sketchup::Entity#parent (method)">#parent</a></td>
      <td><div class='inline'><p>The parent method is used to retrieve the parent of the entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#persistent_id-instance_method" title="Sketchup::Entity#persistent_id (method)">#persistent_id</a></td>
      <td><div class='inline'><p>The <code>#persistent_id</code> method is used to retrieve a unique persistent id assigned to an entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#remove_observer-instance_method" title="Sketchup::Entity#remove_observer (method)">#remove_observer</a></td>
      <td><div class='inline'><p>The remove_observer method is used to remove an observer from the current object.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#set_attribute-instance_method" title="Sketchup::Entity#set_attribute (method)">#set_attribute</a></td>
      <td><div class='inline'><p>The set attribute is used to set the value of an attribute in an attribute dictionary with the given name.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#to_s-instance_method" title="Sketchup::Entity#to_s (method)">#to_s</a></td>
      <td><div class='inline'><p>The <code>#to_s</code> method is used to retrieve the string representation of the entity.</p></div></td>
    </tr>
    <tr class='i_ds'>
      <td><a class='i_m ' href="Entity.html#typename-instance_method" title="Sketchup::Entity#typename (method)">#typename</a></td>
      <td><div class='inline'><p>The typename method retrieves the type of the entity, which will be a string such as âFaceâ, âEdgeâ, or âGroupâ.</p></div></td>
    </tr>
  </tbody>
</table></div>
</div>  <!-- instance_method_summary -->
<h2 class='y_details'>Instance Attribute Details</h2>
<section class='method_details first' id="smooth=-instance_method">
  <h3 class='signature rw first'>
    #<strong>smooth=</strong>(value)  &#x21d2; <code>Boolean</code>  <span class="extras">(<span class='rw'>rw</span>)</span>
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
  <div class="note notetag">
    <strong>Note:</strong>
    <div class='inline'>
<p>The soft and smooth properties are normally set in pairs. You can observer this when the Soften/Smooth Edges feature or holding down Ctrl when using the Eraser Tool.</p>
</div>
  </div>


<p>The <code>#smooth=</code> method is used to set the edge to be smooth.</p>

<p>A smooth edge will cause the shading between connected faces to blend to a smooth transition. The edge will still be visible.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_soft'>soft</span> <span class='op'>=</span> <span class='kw'>true</span>
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_smooth'>smooth</span> <span class='op'>=</span> <span class='kw'>true</span></code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>value</span>
    <span class='type'>(<code>Boolean</code>)</span>
  </li>
</ul>
  <p class='tag_title'>See Also:</p>
  <ul class='see'>
      <li><a href="https://help.sketchup.com/en/article/3000097" target="_parent" title="https://help.sketchup.com/en/article/3000097">https://help.sketchup.com/en/article/3000097</a></li>
      </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="smooth?-instance_method">
  <h3 class='signature rw'>
    #<strong>smooth?</strong>  &#x21d2; <code>Boolean</code>  <span class="extras">(<span class='rw'>rw</span>)</span>
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The <code>#smooth?</code> method is used to retrieve the current smooth setting for an edge.</p>

<p>A smooth edge will cause the shading between connected faces to blend to a smooth transition. The edge will still be visible.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_smooth'>smooth</span> <span class='op'>=</span> <span class='kw'>true</span>
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_smooth?'>smooth?</span></code></pre>
  </div>
  <p class='tag_title'>See Also:</p>
  <ul class='see'>
      <li><a href="https://help.sketchup.com/en/article/3000097" target="_parent" title="https://help.sketchup.com/en/article/3000097">https://help.sketchup.com/en/article/3000097</a></li>
      </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="soft=-instance_method">
  <h3 class='signature rw'>
    #<strong>soft=</strong>(value)  &#x21d2; <code>Boolean</code>  <span class="extras">(<span class='rw'>rw</span>)</span>
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
  <div class="note notetag">
    <strong>Note:</strong>
    <div class='inline'>
<p>The soft and smooth properties are normally set in pairs. You can observe this when the Soften/Smooth Edges feature or holding down Ctrl when using the Eraser Tool.</p>
</div>
  </div>


<p>The <code>#soft=</code> method is used to set the edge to be soft.</p>

<p>A soft edge will cause the connected faces to be treated as a surface. This means that if you have Hidden Geometry off and select one face it will also select all faces connected with soft edges. A soft edge will also appear hidden.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_smooth'>smooth</span> <span class='op'>=</span> <span class='kw'>true</span>
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_soft'>soft</span> <span class='op'>=</span> <span class='kw'>true</span></code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>value</span>
    <span class='type'>(<code>Boolean</code>)</span>
  </li>
</ul>
  <p class='tag_title'>See Also:</p>
  <ul class='see'>
      <li><a href="https://help.sketchup.com/en/article/3000097" target="_parent" title="https://help.sketchup.com/en/article/3000097">https://help.sketchup.com/en/article/3000097</a></li>
      </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="soft?-instance_method">
  <h3 class='signature rw'>
    #<strong>soft?</strong>  &#x21d2; <code>Boolean</code>  <span class="extras">(<span class='rw'>rw</span>)</span>
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The <code>#soft?</code> method is used to retrieve the current soft setting for an edge.</p>

<p>A soft edge will cause the connected faces to be treated as a surface. This means that if you have Hidden Geometry off and select one face it will also select all faces connected with soft edges. A soft edge will also appear hidden.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_soft'>soft</span> <span class='op'>=</span> <span class='kw'>true</span>
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_soft?'>soft?</span></code></pre>
  </div>
  <p class='tag_title'>See Also:</p>
  <ul class='see'>
      <li><a href="https://help.sketchup.com/en/article/3000097" target="_parent" title="https://help.sketchup.com/en/article/3000097">https://help.sketchup.com/en/article/3000097</a></li>
      </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<h2 class='y_details'>Instance Method Details</h2>
<section class='method_details first' id="all_connected-instance_method">
  <h3 class='signature  first'>
    #<strong>all_connected</strong>  &#x21d2; <a href="../Array.html" title="Array (class)">Array</a>&lt;<a href="Entity.html" title="Sketchup::Entity (class)">Sketchup::Entity</a>&gt; 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The all_connected method retrieves all of the entities connected to an edge, including the edge itself.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_model'>model</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>
<span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='id identifier rubyid_model'>model</span>.<span class='id identifier rubyid_active_entities'>active_entities</span>
<span class='id identifier rubyid_points'>points</span> <span class='op'>=</span> [
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>200</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)
]
<span class='comment'># Add the edges to the model
</span><span class='id identifier rubyid_edges'>edges</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_edges'>add_edges</span>(<span class='id identifier rubyid_points'>points</span>)
<span class='id identifier rubyid_connected_entities'>connected_entities</span> <span class='op'>=</span> <span class='id identifier rubyid_edges'>edges</span>.<span class='id identifier rubyid_first'>first</span>.<span class='id identifier rubyid_all_connected'>all_connected</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="../Array.html" title="Array (class)">Array</a>&lt;<a href="Entity.html" title="Sketchup::Entity (class)">Sketchup::Entity</a>&gt;)</span>
&mdash;    <div class='inline'>
<p>the edge and entities connected to that edge</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="common_face-instance_method">
  <h3 class='signature '>
    #<strong>common_face</strong>(edge2)  &#x21d2; <a href="Face.html" title="Sketchup::Face (class)">Sketchup::Face</a><sup>?</sup> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The common_face method is used to identify a face that is common to two edges.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_model'>model</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>
<span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='id identifier rubyid_model'>model</span>.<span class='id identifier rubyid_active_entities'>active_entities</span>
<span class='id identifier rubyid_points'>points</span> <span class='op'>=</span> [
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)
]
<span class='comment'># Add the face to the entities in the model
</span><span class='id identifier rubyid_face'>face</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_face'>add_face</span>(<span class='id identifier rubyid_points'>points</span>)
<span class='id identifier rubyid_edge1'>edge1</span> <span class='op'>=</span> <span class='id identifier rubyid_face'>face</span>.<span class='id identifier rubyid_edges'>edges</span>[<span class='int'>0</span>]
<span class='id identifier rubyid_edge2'>edge2</span> <span class='op'>=</span> <span class='id identifier rubyid_face'>face</span>.<span class='id identifier rubyid_edges'>edges</span>[<span class='int'>1</span>]
<span class='id identifier rubyid_face'>face</span> <span class='op'>=</span> <span class='id identifier rubyid_edge1'>edge1</span>.<span class='id identifier rubyid_common_face'>common_face</span>(<span class='id identifier rubyid_edge2'>edge2</span>)</code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>edge2</span>
    <span class='type'>(<code>Edge</code>)</span>
&mdash;    <div class='inline'>
<p>The face whose edge you are checking for commonality.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="Face.html" title="Sketchup::Face (class)">Sketchup::Face</a>, <code>nil</code>)</span>
&mdash;    <div class='inline'>
<p>the <a href="Face.html" title="Sketchup::Face (class)"><code>Face</code></a> object that is common to the two edges if successful</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="curve-instance_method">
  <h3 class='signature '>
    #<strong>curve</strong>  &#x21d2; <a href="Curve.html" title="Sketchup::Curve (class)">Sketchup::Curve</a><sup>?</sup> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The curve method is used to get the <a href="Curve.html" title="Sketchup::Curve (class)"><code>Curve</code></a> object that this edge belongs to, if any. Note that if the edge is part of an arc instead of a random curve, then this method will return an <a href="ArcCurve.html" title="Sketchup::ArcCurve (class)"><code>ArcCurve</code></a> object.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>
<span class='id identifier rubyid_edges'>edges</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_curve'>add_curve</span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>200</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_curve'>curve</span> <span class='op'>=</span> <span class='id identifier rubyid_edges'>edges</span>[<span class='int'>0</span>].<span class='id identifier rubyid_curve'>curve</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="Curve.html" title="Sketchup::Curve (class)">Sketchup::Curve</a>, <code>nil</code>)</span>
&mdash;    <div class='inline'>
<p>returns a <a href="Curve.html" title="Sketchup::Curve (class)"><code>Curve</code></a> object if it is a curve, nil if it is not a curve</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="end-instance_method">
  <h3 class='signature '>
    #<strong>end</strong>  &#x21d2; <a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The end method is used to retrieve the <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object at the end of the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_vertex'>vertex</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_end'>end</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>)</span>
&mdash;    <div class='inline'>
<p>a <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object if successful</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="explode_curve-instance_method">
  <h3 class='signature '>
    #<strong>explode_curve</strong>  &#x21d2; <code>Edge</code> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The explode_curve method is used to explode the curve that the given edge is a part of.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_model'>model</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>
<span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='id identifier rubyid_model'>model</span>.<span class='id identifier rubyid_active_entities'>active_entities</span>
<span class='id identifier rubyid_edges'>edges</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_curve'>add_curve</span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='id identifier rubyid_edges'>edges</span>[<span class='int'>0</span>]
<span class='id identifier rubyid_exploded_edge'>exploded_edge</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_explode_curve'>explode_curve</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<code>Edge</code>)</span>
&mdash;    <div class='inline'>
<p>an exploded edge object if successful</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="faces-instance_method">
  <h3 class='signature '>
    #<strong>faces</strong>  &#x21d2; <a href="../Array.html" title="Array (class)">Array</a>&lt;<a href="Face.html" title="Sketchup::Face (class)">Sketchup::Face</a>&gt; 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The <code>#faces</code> method is used to retrieve all of the faces common to the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_faces'>faces</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_faces'>faces</span></code></pre>
  </div>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="find_faces-instance_method">
  <h3 class='signature '>
    #<strong>find_faces</strong>  &#x21d2; <code>Integer</code> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The find_faces method is used to create all of the Faces that can be created with this edge. For example, if you use the API to draw three edges that form a triangle, the face between them will not show up because youâve only drawn the edges, but if you call find_faces on one of the edges, the triangle will be filled in.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_model'>model</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>
<span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='id identifier rubyid_model'>model</span>.<span class='id identifier rubyid_active_entities'>active_entities</span>
<span class='id identifier rubyid_points'>points</span> <span class='op'>=</span> [
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>)<span class='comma'>,</span>
  <span class='const'><a href="../Geom.html" title="Geom (module)">Geom</a></span><span class='op'>::</span><span class='const'><a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Point3d</a></span>.<span class='id identifier rubyid_new'><a href="../Geom/Point3d.html#new-class_method" title="Geom::Point3d.new (method)">new</a></span>(<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>)
]
<span class='id identifier rubyid_edges'>edges</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_curve'>add_curve</span>(<span class='id identifier rubyid_points'>points</span>)
<span class='id identifier rubyid_number_of_faces_found'>number_of_faces_found</span> <span class='op'>=</span> <span class='id identifier rubyid_edges'>edges</span>[<span class='int'>0</span>].<span class='id identifier rubyid_find_faces'>find_faces</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<code>Integer</code>)</span>
&mdash;    <div class='inline'>
<p>the number of faces found</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="length-instance_method">
  <h3 class='signature '>
    <div class='inline-block'>
      <span class='overload'>#<strong>length</strong>  &#x21d2; <a href="../Length.html" title="Length (class)">Length</a> </span>
      <span class='overload'>#<strong>length</strong>(transform)  &#x21d2; <a href="../Length.html" title="Length (class)">Length</a> </span>
    </div>
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The <code>#length</code> method is used to retrieve the length of an edge in current units.</p>

<p>You can pass in an optional <a href="../Geom/Transformation.html" title="Geom::Transformation (class)"><code>::Geom::Transformation</code></a> (or an array that can represent a transformation), to correct for a parent groupâs transformation. For example, if an edge is inside of a group that is scaled to 200%, the length method will return the unscaled length of the edge. So by passing a 200% transformation object to this method, you can account for that to get the âvisualâ length of the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_length'>length</span></code></pre>
  </div>
  <p class='tag_title'>Overloads:</p>
  <ul class='overload'>

      <li class='overload_item'>
        <span class='signature'>#<strong>length</strong>  &#x21d2; <a href="../Length.html" title="Length (class)">Length</a> </span>
        <div class='docstring'>
  <div class='discussion'>
    
  </div>
</div>
<div class='tags'>
  <p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="../Length.html" title="Length (class)">Length</a>)</span>
&mdash;    <div class='inline'>
<p>the length of the edge</p>
</div>
  </li>
</ul>

</div>

      </li>

      <li class='overload_item'>
        <span class='signature'>#<strong>length</strong>(transform)  &#x21d2; <a href="../Length.html" title="Length (class)">Length</a> </span>
        <div class='docstring'>
  <div class='discussion'>
    
  </div>
</div>
<div class='tags'>
  <p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>transform</span>
    <span class='type'>(<a href="../Geom/Transformation.html" title="Geom::Transformation (class)">Geom::Transformation</a>)</span>
&mdash;    <div class='inline'>
<p>A Transformation object or array that can be interpreted as a Transformation object.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="../Length.html" title="Length (class)">Length</a>)</span>
&mdash;    <div class='inline'>
<p>the length of the edge</p>
</div>
  </li>
</ul>

</div>

      </li>
  </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="line-instance_method">
  <h3 class='signature '>
    #<strong>line</strong>  &#x21d2; <a href="../Array.html" title="Array (class)">Array</a>(<a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Geom::Point3d</a>, <a href="../Geom/Vector3d.html" title="Geom::Vector3d (class)">Geom::Vector3d</a>) 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The line method is used to retrieve the line defined by the edge. Lines in SketchUp arenât visible entities but geometric constructs represented by an <a href="../Array.html" title="Array (class)"><code>::Array</code></a> with a Point3d and a Vector3d. See the <a href="../Geom.html" title="Geom (module)"><code>::Geom</code></a> module and the <a href="../Array.html" title="Array (class)"><code>::Array</code></a> class for more information on lines.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span><span class='int'>0</span><span class='comma'>,</span><span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_line'>line</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_line'>line</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="../Array.html" title="Array (class)">Array</a>(<a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Geom::Point3d</a>, <a href="../Geom/Vector3d.html" title="Geom::Vector3d (class)">Geom::Vector3d</a>))</span>
&mdash;    <div class='inline'>
<p>an array with a Point3d object and a Vector3d object.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="other_vertex-instance_method">
  <h3 class='signature '>
    #<strong>other_vertex</strong>(vertex1)  &#x21d2; <a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The other_vertex method is used to find the opposite vertex given one vertex of the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span>[<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='comment'># Get the end vertex of an edge
</span><span class='id identifier rubyid_vertex'>vertex</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_end'><a href="#end-instance_method" title="Sketchup::Edge#end (method)">end</a></span>
<span class='comment'># Should find the starting vertex
</span><span class='id identifier rubyid_other_vertex'>other_vertex</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_other_vertex'>other_vertex</span>(<span class='id identifier rubyid_vertex'>vertex</span>)</code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>vertex1</span>
    <span class='type'>(<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>)</span>
&mdash;    <div class='inline'>
<p>One of the <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> objects associated with the edge.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>)</span>
&mdash;    <div class='inline'>
<p>the other <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object associated with the edge</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="reversed_in?-instance_method">
  <h3 class='signature '>
    #<strong>reversed_in?</strong>(face)  &#x21d2; <code>Boolean</code> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The <code>#reversed_in?</code> method is used to determine if the edge is reversed in a faceâs bounding loop.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_model'>model</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>
<span class='id identifier rubyid_entities'>entities</span> <span class='op'>=</span> <span class='id identifier rubyid_model'>model</span>.<span class='id identifier rubyid_active_entities'>active_entities</span>
<span class='id identifier rubyid_points'>points</span> <span class='op'>=</span> []
<span class='id identifier rubyid_points'>points</span>[<span class='int'>0</span>] <span class='op'>=</span> [<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]
<span class='id identifier rubyid_points'>points</span>[<span class='int'>1</span>] <span class='op'>=</span> [<span class='int'>9</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]
<span class='id identifier rubyid_points'>points</span>[<span class='int'>2</span>] <span class='op'>=</span> [<span class='int'>9</span><span class='comma'>,</span> <span class='int'>9</span><span class='comma'>,</span> <span class='int'>0</span>]
<span class='id identifier rubyid_points'>points</span>[<span class='int'>3</span>] <span class='op'>=</span> [<span class='int'>0</span><span class='comma'>,</span> <span class='int'>9</span><span class='comma'>,</span> <span class='int'>0</span>]
<span class='comment'># Add the face to the entities in the model.
</span><span class='id identifier rubyid_face'>face</span> <span class='op'>=</span> <span class='id identifier rubyid_entities'>entities</span>.<span class='id identifier rubyid_add_face'>add_face</span>(<span class='id identifier rubyid_points'>points</span>)
<span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='id identifier rubyid_face'>face</span>.<span class='id identifier rubyid_edges'>edges</span>[<span class='int'>0</span>]
<span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_reversed_in?'>reversed_in?</span>(<span class='id identifier rubyid_face'>face</span>)</code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>face</span>
    <span class='type'>(<a href="Face.html" title="Sketchup::Face (class)">Sketchup::Face</a>)</span>
&mdash;    <div class='inline'>
<p>The face that is bounded by the edge.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<code>Boolean</code>)</span>
&mdash;    <div class='inline'>
<p><code>true</code> if the edge is reversed, <code>false</code> if it is not reversed. <code>nil</code> if the edge and face is not connected.</p>
</div>
  </li>
</ul>
  <p class='tag_title'>See Also:</p>
  <ul class='see'>
      <li><a href="EdgeUse.html" title="Sketchup::EdgeUse (class)"><code>EdgeUse</code></a></li>
          <li><a href="Loop.html" title="Sketchup::Loop (class)"><code>Loop</code></a></li>
      </ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="split-instance_method">
  <h3 class='signature '>
    #<strong>split</strong>(position)  &#x21d2; <code>Edge</code> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The split method is used to  to split an edge into two or more distinct edges. If a Point3d is given, it must be a point that is on the <code>Edge</code>.</p>

<p>If a Float is given, it is a number between 0 and 1 that gives the relative position along the edge at which to split it.  For example, edge.split(0.5) will split the <code>Edge</code> at its midpoint. This split position is measured from the <code>Edge</code>.start.</p>

<p>Returns the new <code>Edge</code> that was created as a result of splitting this one.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_new_edge'>new_edge</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_split'>split</span>(<span class='float'>0.5</span>)</code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>position</span>
    <span class='type'>(<a href="../Geom/Point3d.html" title="Geom::Point3d (class)">Geom::Point3d</a>)</span>
&mdash;    <div class='inline'>
<p>A Point3d object whose location is along the edge, or a Float between 0.0 and 1.0 defining how far along the edge to split.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<code>Edge</code>)</span>
&mdash;    <div class='inline'>
<p>the new <code>Edge</code> object that was split off the old one if successful</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="start-instance_method">
  <h3 class='signature '>
    #<strong>start</strong>  &#x21d2; <a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The start method is used to retrieve the <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object at the start of the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_vertex'>vertex</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_start'>start</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>)</span>
&mdash;    <div class='inline'>
<p>a <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> object if successful</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="used_by?-instance_method">
  <h3 class='signature '>
    #<strong>used_by?</strong>(element)  &#x21d2; <code>Boolean</code> 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The used_by? method is used to see if an edge is used by a given <a href="Face.html" title="Sketchup::Face (class)"><code>Face</code></a> or <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a>.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span>[<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='comment'># Returns a vertex
</span><span class='id identifier rubyid_vertex'>vertex</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_start'><a href="#start-instance_method" title="Sketchup::Edge#start (method)">start</a></span>
<span class='comment'># Check to see if the edge is used by the Vertex.
</span><span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_used_by?'>used_by?</span>(<span class='id identifier rubyid_vertex'>vertex</span>)</code></pre>
  </div>
<p class='tag_title'>Parameters:</p>
<ul class='param'>
  <li>
    <span class='name'>element</span>
    <span class='type'>(<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>, <a href="Face.html" title="Sketchup::Face (class)">Sketchup::Face</a>)</span>
&mdash;    <div class='inline'>
<p>A Vertex or <a href="Face.html" title="Sketchup::Face (class)"><code>Face</code></a> object.</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>

<section class='method_details' id="vertices-instance_method">
  <h3 class='signature '>
    #<strong>vertices</strong>  &#x21d2; <a href="../Array.html" title="Array (class)">Array</a>&lt;<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>&gt; 
  </h3>
<div class='docstring'>
  <div class='discussion'>
    
<p>The vertices method is used to retrieve the vertices on the edge.</p>

  </div>
</div>
<div class='tags'>
    <div class='examples'>
    <p class='tag_title'>Examples:</p>
      <pre class='example code ruby'><code><span class='id identifier rubyid_edge'>edge</span> <span class='op'>=</span> <span class='const'><a href="../Sketchup.html" title="Sketchup (module)">Sketchup</a></span>.<span class='id identifier rubyid_active_model'><a href="../Sketchup.html#active_model-class_method" title="Sketchup.active_model (method)">active_model</a></span>.<span class='id identifier rubyid_entities'><a href="Model.html#entities-instance_method" title="Sketchup::Model#entities (method)">entities</a></span>.<span class='id identifier rubyid_add_line'><a href="Entities.html#add_line-instance_method" title="Sketchup::Entities#add_line (method)">add_line</a></span>([<span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span><span class='comma'>,</span> <span class='int'>0</span>]<span class='comma'>,</span> [<span class='int'>100</span><span class='comma'>,</span> <span class='int'>100</span><span class='comma'>,</span> <span class='int'>0</span>])
<span class='id identifier rubyid_vertices'>vertices</span> <span class='op'>=</span> <span class='id identifier rubyid_edge'>edge</span>.<span class='id identifier rubyid_vertices'>vertices</span></code></pre>
  </div>
<p class='tag_title'>Returns:</p>
<ul class='return'>
  <li>
    <span class='type'>(<a href="../Array.html" title="Array (class)">Array</a>&lt;<a href="Vertex.html" title="Sketchup::Vertex (class)">Sketchup::Vertex</a>&gt;)</span>
&mdash;    <div class='inline'>
<p>an array of <a href="Vertex.html" title="Sketchup::Vertex (class)"><code>Vertex</code></a> objects</p>
</div>
  </li>
</ul>
<p class='tag_title'>Version:</p>
<ul class='version'>
  <li>
    <div class='inline'>
<p>SketchUp 6.0</p>
</div>
  </li>
</ul>

</div>

</section>


<div id='footer'></div>
</div> <!-- content  -->
</div> <!-- y_main   -->
</body>
</html>